services:
  backend:
    build:
      context: backend
    command: ["npm", "run", "start"]
    ports:
      - "5001:5001"
    networks:
      - bt-takehome
    depends_on:
      - mongodb
    restart: always
    volumes:
      - ./backend/src:/backend/src

  frontend:
    build:
      context: frontend
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    networks:
      - bt-takehome
    depends_on:
      - backend
    restart: "no"
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - bt-takehome
    restart: always
    volumes:
      - ./db:/data/db

networks:
  bt-takehome:
    name: bt-takehome
